#!/bin/bash

# Script para establecer zsh como el shell de nuestro usuario e instalar los
# archivos de configuracioń
# - Invocado en /installer/stage3.sh

if [ "$(id -u)" -eq 0 ]; then
	echo "Error: Este script no debe ejecutarse como root." >&2
	exit 1
fi

# Crear la carpeta ~/.config
mkdir -p "$HOME/.config"

# Instalar los archivos de configuración
"$HOME/.dotfiles/update.sh"

# Selecciona zsh como el shell del usuario
echo "ZDOTDIR=\$HOME/.config/zsh" | sudo tee /etc/zsh/zshenv
sudo chsh -s /bin/zsh "$USER"
