#!/bin/bash

# Script para recompilar las aplicaciones suckless
# - Invocado por /update.sh

# Se termina la ejecución de toda la tubería despúes del primer fallo
set -o pipefail

if [ "$(id -u)" -eq 0 ]; then
	echo "Error: Este script no debe ejecutarse como root." >&2
	exit 1
fi

# Obtener el DPI desde Xresources
DPI="$(grep -oP "Xft.dpi:\K[0-9]*" "$HOME"/.config/Xresources)"

# Directorio base para las aplicaciones suckless
SUCKLESS_BASE="$HOME/.dotfiles/suckless"

# Función para compilar una aplicación suckless
compile_suckless_app() {
	local APP="$1"
	local SUCKLESS_DIR="$SUCKLESS_BASE/$APP"

	# Limpiar directorio
	sudo make clean --directory "$SUCKLESS_DIR" >/dev/null 2>&1 || return 1

	# Modificar config.h si el DPI es alto
	if [ "$DPI" -ge 192 ] && [ "$APP" != "dwmblocks" ]; then
		sed 's/pixelsize=[0-9]*/pixelsize=38/g' "$SUCKLESS_DIR"/config.def.h |
			tee "$SUCKLESS_DIR"/config.h >/dev/null

		if [ "$APP" = "dwm" ]; then
			sed -i 's/user_bh.*=.*[0-9]*;/user_bh=24;/g' "$SUCKLESS_DIR/config.h"
		fi
	fi

	# Compilar e instalar
	sudo make install --directory "$SUCKLESS_DIR" >/dev/null 2>&1 &&
		echo "$APP compilado con éxito" || return 1
}

# Recompilar aplicaciones suckless
for app in dmenu dwm dwmblocks st; do
	compile_suckless_app "$app" || echo "Error: Falló la compilación de $app."
done

# Configurar Eclipse para HDPI (si está instalado)
if command -v eclipse &>/dev/null; then
	ECLIPSE_WRAPPER="/usr/local/bin/eclipse"
	# Si no existe ya el script wrapper o no está configurado para HDPI
	if [ ! -f "$ECLIPSE_WRAPPER" ] || ! grep -q "GDK_DPI_SCALE=0.5 GDK_SCALE=2" "$ECLIPSE_WRAPPER" 2>/dev/null; then
		# Crear el script y hacerlo ejecutable
		cat <<-EOF | sudo tee "$ECLIPSE_WRAPPER"
			#!/bin/bash
			GDK_DPI_SCALE=0.5 GDK_SCALE=2 /usr/bin/eclipse "\$@"
		EOF
		chmod +x "$ECLIPSE_WRAPPER"

		echo "Eclipse configurado para HDPI."
	fi
else
	echo "Eclipse no está instalado, omitiendo configuración."
fi
