#!/bin/sh

# Script para construir e instalar yay
# - Invocado en /installer/stage3.sh

if [ "$(id -u)" -eq 0 ]; then
	echo "Error: Este script no debe ejecutarse como root." >&2
	exit 1
fi

# Directorio temporal para clonar el repositorio de yay
TMP_DIR="/tmp/yay_install_temp"

# Crear el directorio temporal
mkdir -p "$TMP_DIR"

# Clonar el repositorio
git clone --depth 1 https://aur.archlinux.org/yay.git "$TMP_DIR" >/dev/null

# Construimos e instalamos yay
sh -c "cd $TMP_DIR && makepkg -si --noconfirm"
