#!/bin/sh

# Script para darle acceso al usuario al audio de baja latencia, además de
# añadirlo a los grupos: realtime, audio, video, optical y uucp
# - Invocado en /installer/stage3.sh

# Configurar el audio de baja latencia

# Verificar si el script se ejecuta como root
if [ "$(id -u)" -ne 0 ]; then
	echo "Error: Este script debe ejecutarse como root." >&2
	exit 1
fi

# Obtener el nombre de usuario con UID 1000 (generalmente el primer usuario no root)
RUSER="$(getent passwd 1000 | cut -d: -f1)"
if [ -z "$RUSER" ]; then
	echo "Error: No se pudo encontrar un usuario con UID 1000." >&2
	exit 1
fi

# Añadimos el usuario a los grupos desados
usermod -aG realtime,audio,video,optical,uucp "$RUSER"

# Permite al usuario (en el grupo "audio") utilizar dispositivos de audio con
# prioridad elevada y acceso a recursos extendidos.
cat <<-EOF | tee -a /etc/security/limits.conf
	    @audio - rtprio 95
	    @audio - memlock unlimited
	    $RUSER hard nofile 524288
EOF
