#!/bin/bash

set -o pipefail

if [ "$(id -u)" -ne 0 ]; then
	echo "Error: Este script debe ejecutarse como root." >&2
	exit 1
fi

TIMEZONE="$(readlink /etc/localtime | sed 's|.*/zoneinfo/||')"

# Inicializamos un contador
COUNTER=1

# Ejecutamos curl en un bucle hasta que la variable este definida
# porque aveces no se se recibe correctamente la fecha.

while true; do

	[ -z "$CURRENT_TIME" ] && CURRENT_TIME=$(
		curl -s \
		"http://worldtimeapi.org/api/timezone/$TIMEZONE" | \
		jq -r '.datetime' | cut -d. -f1 | sed 's/T/ /'
	)

	[ -z "$CURRENT_TIME" ] && CURRENT_TIME=$(
		curl -s \
		"https://timeapi.io/api/Time/current/zone?timeZone=$TIMEZONE" | \
		grep -oP '"dateTime":"\K[^"]+' | cut -d. -f1 | sed 's/T/ /'
	)

	# Si la variable esta establecida, salimos del bucle
	[ -n "$CURRENT_TIME" ] && break

	# Si el contador es mayor a 5, salimos del bucle
	if [ "$COUNTER" -ge 5 ]; then
		echo "Error: No se pudo obtener la hora después de 5 intentos." >&2
		exit 1
	fi

	# Incrementamos el contador
	COUNTER=$((COUNTER + 1))

	sleep 5

done

hwclock --set --date="$CURRENT_TIME" && \
hwclock --hctosys
