#!/bin/sh

# El paquete tuxguitar-bin guarda el archivo .desktop de la aplicación
# en un directorio no estándar. Con esto enlazamos los archivos
# necesarios en /usr/share para que el sistema los reconozca.

ln -s /opt/tuxguitar/share/applications/tuxguitar.desktop \
	/usr/share/applications/

[ ! -d /usr/share/icons/hicolor/96x96/apps ] &&
	mkdir -p /usr/share/icons/hicolor/96x96/apps

ln -s /opt/tuxguitar/share/pixmaps/tuxguitar.png \
	/usr/share/icons/hicolor/96x96/apps/

ln -s /usr/bin/tuxguitar-bin /usr/bin/tuxguitar
