#!/bin/sh
# Este archivo no se linkea, se instala con install -m 755
# Al hacer cambios no olvides volverlo a instalar con:
# sudo install -m 755 "$HOME/.dotfiles/assets/system/auto-suspend-loop" /usr/local/bin/auto-suspend-loop

while true; do
	/usr/local/bin/auto-suspend
	sleep 60
done
