#!/bin/sh
# Este archivo no se linkea, se instala con install -m 755
# Al hacer cambios no olvides volverlo a instalar con:
# sudo install -m 755 "$HOME/.dotfiles/assets/system/auto-suspend" /usr/local/bin/auto-suspend

# Verifica el nivel de batería
battery_level=$(cat /sys/class/power_supply/BAT0/capacity)
battery_status=$(cat /sys/class/power_supply/BAT0/status)

if [ "$battery_status" = "Discharging" ] && [ "$battery_level" -le 10 ]; then
	/usr/bin/loginctl suspend
fi
