#!/bin/sh

# Verifica el nivel de batería
battery_level=$(cat /sys/class/power_supply/BAT0/capacity)
battery_status=$(cat /sys/class/power_supply/BAT0/status)

if [ "$battery_status" = "Discharging" ] && [ "$battery_level" -le 10 ]; then
	/usr/bin/loginctl suspend
fi
