#!/bin/sh
# Este archivo no se linkea, se instala con install -m 755
# Al hacer cambios no olvides volverlo a instalar con:
# sudo install -m 755 "$HOME/.dotfiles/assets/system/nm-restart" /lib/elogind/system-sleep/nm-restart

case "${1-}" in
'post')
	/usr/bin/rc-service NetworkManager "restart"
	sleep 1
	/usr/bin/rc-service netmount "restart"
	/usr/bin/rc-service nptd "restart"
	[ -e "/usr/bin/libvirtd" ] && /usr/bin/rc-service libvirtd "restart"
	;;
esac
