# dwm - dynamic window manager
# Consulta el archivo LICENSE para los detalles de derechos de autor y licencia.

include config.mk

SRC = drw.c dwm.c util.c
OBJ = ${SRC:.c=.o}

all: dwm

.c.o:
	${CC} -c ${CFLAGS} $<

${OBJ}: config.h config.mk

config.h:
	cp config.def.h $@

dwm: ${OBJ}
	${CC} -o $@ ${OBJ} ${LDFLAGS}

clean:
	rm -f *.o dwm config.h

install: all
	mkdir -p ${DESTDIR}${PREFIX}/bin
	install -Dm 755 dwm ${DESTDIR}${PREFIX}/bin
	install -Dm 755 layoutmenu.sh ${DESTDIR}${PREFIX}/bin
	mkdir -p ${DESTDIR}${MANPREFIX}/man1
	sed "s/VERSION/${VERSION}/g" < dwm.1 > ${DESTDIR}${MANPREFIX}/man1/dwm.1
	chmod 644 ${DESTDIR}${MANPREFIX}/man1/dwm.1

uninstall:
	rm -f ${DESTDIR}${PREFIX}/bin/dwm \
		${DESTDIR}${PREFIX}/bin/layoutmenu.sh \
		${DESTDIR}${MANPREFIX}/man1/dwm.1

.PHONY: all clean install uninstall
