#!/bin/sh

case "$1" in
	pre)
		/usr/bin/rc-service libvirtd "stop"
		/usr/bin/rc-service netmount "stop"
		/usr/bin/rc-service nptd "stop"
		/usr/bin/rc-service NetworkManager "stop"
		;;
	post)
		/usr/bin/rc-service NetworkManager "start"
		/usr/bin/rc-service nptd "start"
		/usr/bin/rc-service netmount "start"
		/usr/bin/rc-service libvirtd "start"
	;;
esac
