#!/bin/sh

[ -f "$HOME/.config/Xresources" ] && xrdb "$HOME/.config/Xresources"

if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
		# shellcheck source=/dev/null
		[ -x "$f" ] && "$f" &
	done
fi

dbus-update-activation-environment --all

while true; do
	dwm >/dev/null 2>&1
done
